
version: "3.9"

x-network: &default-network
  networks:
    - graph-net

x-env: &default-env
  environment:
    NEO4J_URI: bolt://neo4j:7687
    NEO4J_USER: neo4j
    NEO4J_PASSWORD: local_neo4j_pw
    REDIS_URL: redis://redis:6379/0
    OPENAI_API_KEY: ${OPENAI_API_KEY:?err}
    AUTH_SECRET: ${AUTH_SECRET:?err}
    PYTHONUNBUFFERED: 1

volumes:
  neo4j_data:
  redis_data:

networks:
  graph-net:
    driver: bridge

services:
  neo4j:
    image: neo4j:5-enterprise
    container_name: graph-db
    <<: *default-network
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_db_memory_pagecache_size: 1G
      NEO4J_PLUGINS: '["graph-data-science","n10s"]'
      NEO4J_AUTH: "neo4j/local_neo4j_pw"
    ports:
      - "7474:7474"
      - "7687:7687"

  redis:
    image: redis:7-alpine
    container_name: graph-redis
    <<: *default-network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: graph-api
    <<: [*default-network, *default-env]
    depends_on:
      - neo4j
      - redis
    ports:
      - "8000:8000"
    command: >
      bash -lc "uvicorn app.main:app --host 0.0.0.0 --port 8000"

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: graph-celery
    <<: [*default-network, *default-env]
    depends_on:
      - api
      - redis
    command: >
      bash -lc "celery -A app.tasks worker --loglevel=info"

  mcp-agent:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    container_name: graph-mcp
    <<: [*default-network, *default-env]
    depends_on:
      - api
    ports:
      - "3911:3911"
    command: >
      bash -lc "python serve.py"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: graph-web
    <<: [*default-network, *default-env]
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    command: >
      bash -lc "npm run dev"
